# Generated by Django 5.2.9 on 2026-05-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_adjust_transfer_price_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='shellydevice',
            name='minimum_run_hours_per_day',
            field=models.IntegerField(default=0, help_text='Minimum hours to keep assigned from the cheapest periods (0-24)'),
        ),
    ]
