# Generated by Django 5.2.9 on 2026-06-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_deviceassignment_assignment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shellydevice',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
