# Generated by Django 5.2.9 on 2026-06-15 11:49

import app.utils.time_utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_min_temperature_add_summer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceassignment',
            name='assignment_type',
            field=models.CharField(choices=[('cheapest', 'Cheapest Hours'), ('threshold', 'Price Threshold'), ('forced_min', 'Forced — Min Temperature'), ('manual', 'Manual'), ('removed_overheat', 'Removed — Overheating')], default='cheapest', help_text='Reason this period was assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='shellytemperature',
            name='min_temperature_summer',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum temperature threshold Apr 1 – Aug 31 (summer season)', max_digits=5, verbose_name='Min temperature (summer)'),
        ),
        migrations.AlterField(
            model_name='shellytemperature',
            name='min_temperature_winter',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum temperature threshold Sep 1 – Mar 31 (winter season)', max_digits=5, verbose_name='Min temperature (winter)'),
        ),
        migrations.CreateModel(
            name='EVCharger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('familiar_name', models.CharField(max_length=255)),
                ('backend', models.CharField(choices=[('tuya', 'Tuya IoT Platform')], default='tuya', max_length=50)),
                ('tuya_client_id', models.CharField(blank=True, default='', max_length=255)),
                ('tuya_client_secret', models.CharField(blank=True, default='', max_length=255)),
                ('tuya_device_id', models.CharField(blank=True, default='', max_length=255)),
                ('tuya_base_url', models.URLField(default='https://openapi.tuyaeu.com', help_text='Regional Tuya OpenAPI URL (e.g. https://openapi.tuyaeu.com for Europe)', max_length=512)),
                ('charge_current_a', models.IntegerField(default=6, help_text='Default charging current in amperes (1-32 A)')),
                ('run_hours_per_day', models.IntegerField(default=0, help_text='Hours to charge per day (0 = no automatic scheduling)')),
                ('day_transfer_price', models.DecimalField(decimal_places=1, default=0, help_text='Day-time transfer price (c/kWh, 07:00-21:59)', max_digits=6)),
                ('night_transfer_price', models.DecimalField(decimal_places=1, default=0, help_text='Night-time transfer price (c/kWh, 22:00-06:59)', max_digits=6)),
                ('auto_assign_price_threshold', models.DecimalField(decimal_places=1, default=0, help_text='Always assign periods at or below this total price (c/kWh, 0 = disabled)', max_digits=6)),
                ('status', models.IntegerField(default=1, help_text='1 = automation enabled, 0 = disabled')),
                ('is_charging', models.BooleanField(default=False)),
                ('work_state', models.CharField(blank=True, default='', max_length=64)),
                ('connection_state', models.CharField(blank=True, default='', max_length=64)),
                ('power_w', models.IntegerField(default=0)),
                ('temp_c', models.IntegerField(default=0)),
                ('session_energy_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('total_energy_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('last_contact', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EV Charger',
                'verbose_name_plural': 'EV Chargers',
            },
        ),
        migrations.AddField(
            model_name='devicelog',
            name='ev_charger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app.evcharger'),
        ),
        migrations.CreateModel(
            name='EVChargerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assignment_type', models.CharField(choices=[('cheapest', 'Cheapest Hours'), ('threshold', 'Price Threshold'), ('manual', 'Manual')], default='cheapest', help_text='Reason this period was assigned', max_length=20)),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.evcharger')),
                ('electricity_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.electricityprice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EV Charger Assignment',
                'verbose_name_plural': 'EV Charger Assignments',
            },
        ),
        migrations.CreateModel(
            name='EVChargerEnergyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=app.utils.time_utils.TimeUtils.now_utc)),
                ('session_energy_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('total_energy_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('is_charging', models.BooleanField(default=False)),
                ('power_w', models.IntegerField(default=0)),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_logs', to='app.evcharger')),
            ],
            options={
                'verbose_name': 'EV Charger Energy Log',
                'verbose_name_plural': 'EV Charger Energy Logs',
            },
        ),
    ]
