# Generated by Django 5.2.9 on 2026-06-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_deviceassignment_assignment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcharger',
            name='charge_current_reduced_a',
            field=models.IntegerField(default=3, help_text='Reduced charging current used when other high-power devices are running, to protect fuses (1-32 A)'),
        ),
        migrations.AlterField(
            model_name='evcharger',
            name='charge_current_a',
            field=models.IntegerField(default=6, help_text='Normal charging current in amperes (1-32 A)'),
        ),
    ]
