# Generated by Django 5.2.9 on 2026-06-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_evcharger_charge_current_reduced_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceassignment',
            name='energy_kwh',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Energy used during this period (kWh), reserved for future use', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='evchargerassignment',
            name='energy_kwh',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Energy used during this period (kWh), filled in by scheduler after the period ends', max_digits=8, null=True),
        ),
    ]
