# Generated by Django 5.2.9 on 2026-06-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_add_energy_kwh_to_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcharger',
            name='session_started_at',
            field=models.DateTimeField(blank=True, help_text='When the current/last charging session started (UTC)', null=True),
        ),
        migrations.AddField(
            model_name='evchargerassignment',
            name='charge_current_a',
            field=models.IntegerField(blank=True, help_text='Charge current (A) recorded during this slot — used to weight session energy split', null=True),
        ),
        migrations.AlterField(
            model_name='evchargerassignment',
            name='energy_kwh',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Energy used during this period (kWh), filled in after session ends', max_digits=8, null=True),
        ),
    ]
