# Generated by Django 5.2.9 on 2026-06-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_ev_session_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shellytemperature',
            name='hoped_temperature',
        ),
        migrations.AddField(
            model_name='shellytemperature',
            name='headroom_summer',
            field=models.DecimalField(decimal_places=1, default=4, help_text='Apr 1 – Aug 31: stop assigning this many degrees below max temperature (0 = disabled)', max_digits=4, verbose_name='Headroom (summer, °C)'),
        ),
        migrations.AddField(
            model_name='shellytemperature',
            name='headroom_winter',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Sep 1 – Mar 31: stop assigning this many degrees below max temperature (0 = disabled)', max_digits=4, verbose_name='Headroom (winter, °C)'),
        ),
        migrations.AlterField(
            model_name='deviceassignment',
            name='assignment_type',
            field=models.CharField(choices=[('cheapest', 'Cheapest Hours'), ('threshold', 'Price Threshold'), ('forced_min', 'Forced — Min Temperature'), ('manual', 'Manual'), ('removed_overheat', 'Removed — Overheating'), ('removed_headroom', 'Removed — Headroom')], default='cheapest', help_text='Reason this period was assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='shellytemperature',
            name='max_temperature',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum temperature threshold — assignments are removed above this', max_digits=5),
        ),
        migrations.AlterField(
            model_name='shellytemperature',
            name='min_temperature_summer',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Failsafe temperature Apr 1 – Aug 31 — forced heating activates below this', max_digits=5, verbose_name='Min temperature (summer)'),
        ),
        migrations.AlterField(
            model_name='shellytemperature',
            name='min_temperature_winter',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Failsafe temperature Sep 1 – Mar 31 — forced heating activates below this', max_digits=5, verbose_name='Min temperature (winter)'),
        ),
    ]
